Add documentation for configurations
Leaf-Agriculture/docs pull request #106
Opened 2021-04-05 13:52 UTC by gabrieltron

2021-04-05 13:53 UTC, gabrieltron commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Docs] Update docs to include config](https://trello.com/c/vq7oygYJ/960-docs-update-docs-to-include-config)

2021-04-05 15:49 UTC, fabyan-alexander requested changes
Nice update! Just a few typos and some small suggestions

2021-04-05 15:49 UTC, fabyan-alexander commented on docs/configurations_endpoints.md
> +      'https://api.withleaf.io/services/config/api/configs/${LEAF_USER_ID}'
Incorrect variable name and single quote won't replace the variable
```suggestion
  curl -X GET \
      -H "Authorization: Bearer ${TOKEN}" \
      "https://api.withleaf.io/services/config/api/configs/${LEAF_USER_ID}"
```

2021-04-05 15:49 UTC, fabyan-alexander commented on docs/configurations_endpoints.md
> +      'https://api.withleaf.io/service/configs/api/configs'
Use double quote to allow the variables to be processed
```suggestion
  curl -X GET \
      -H "Authorization: Bearer ${TOKEN}" \
      "https://api.withleaf.io/service/configs/api/configs"
```

2021-04-05 15:49 UTC, fabyan-alexander commented on docs/configurations_endpoints.md
> +      'https://api.withleaf.io/services/config/api/configs/${LEAF_USER_ID}'
Use double quote to allow the variables to be processed
```suggestion
  curl -X POST \
      -H "Authorization: Bearer ${TOKEN}" \
      -d '{ "operationImageCreation": true, "operationsSummaryCreation": true, "fieldsAutoSync": true }' \
      "https://api.withleaf.io/services/config/api/configs/${LEAF_USER_ID}"
```

2021-04-05 15:49 UTC, fabyan-alexander commented on docs/configurations_endpoints.md
> +      'https://api.withleaf.io/services/config/api/configs'
Use double quote to allow the variables to be processed
```suggestion
  curl -X PUT \
      -H "Authorization: Bearer ${TOKEN}" \
      -d '{ "operationImageCreation": true, "operationsSummaryCreation": true, "fieldsAutoSync": true }' \
      'https://api.withleaf.io/services/config/api/configs'
```

2021-04-05 15:49 UTC, fabyan-alexander commented on docs/configurations_endpoints.md
> +      'https://api.withleaf.io/services/config/api/configs/${LEAF_USER_ID}'
Use double quote to allow the variables to be processed
```suggestion
  curl -X PUT \
      -H "Authorization: Bearer ${TOKEN}" \
      -d '{ "operationImageCreation": true, "operationsSummaryCreation": true, "fieldsAutoSync": true }' \
      "https://api.withleaf.io/services/config/api/configs/${LEAF_USER_ID}"
```

2021-04-05 15:49 UTC, fabyan-alexander commented on docs/configurations_endpoints.md
> +      'https://api.withleaf.io/services/config/api/configs/${LEAF_USER_ID}'
Use double quote to allow the variables to be processed
```suggestion
  curl -X DELETE \
      -H "Authorization: Bearer ${TOKEN}" \
      "https://api.withleaf.io/services/config/api/configs/${LEAF_USER_ID}"
```

2021-04-05 15:49 UTC, fabyan-alexander commented on docs/configurations_endpoints.md
> +containing the configurations to be set. All entries are optional, if missing the configuration will be inherited from the Api Owner's Configuration.
```suggestion
Creates the Configuration for the Leaf User `leafUserId`. A request body must be provided
containing the configurations to be set. All entries are optional, any missing configuration will be inherited from the Api Owner's Configuration.
```

2021-04-05 15:49 UTC, fabyan-alexander commented on docs/configurations_endpoints.md
> +containing the configurations to be set. All entries are optional, if missing the configuration will be inherited from the Api Owner's Configuration.
```suggestion
Updates the Configuration for the Leaf User `leafUserId`. A request body must be provided
containing the configurations to be set. All entries are optional, any missing configuration will be inherited from the Api Owner's Configuration.
```

2021-04-05 15:49 UTC, fabyan-alexander commented on docs/configurations_endpoints.md
> +containing the configurations to be set. All entries are required.
```suggestion
Updates the Configuration for the Api Owner. A request body must be provided
containing the configurations to be set. All entries are required.
```

2021-04-05 15:49 UTC, fabyan-alexander commented on docs/configurations_endpoints.md
> +### Delete Leaf User's Configuraiton
```suggestion
### Delete Leaf User's Configuration
```

2021-04-06 13:14 UTC, fabyan-alexander approved these changes
Approved

2021-04-06 14:15 UTC, fabyan-alexander commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Config] Fix typo in property name](https://trello.com/c/GVXu8Zo6/969-config-fix-typo-in-property-name)

2021-04-06 14:53 UTC, CarlosSam approved these changes

2021-04-19 19:16 UTC, fabyan-alexander requested changes
Just a small fix

2021-04-19 19:16 UTC, fabyan-alexander commented on docs/configurations_endpoints.md
> +[Update Leaf User's Configuraiton][7] | <span class="badge badge--warning">PATCH</span> `/configs/{leafUserId}`
```suggestion
[Update Api Owner's Configuraiton][7] | <span class="badge badge--warning">PATCH</span> `/configs/{leafUserId}`
```

2021-04-20 17:59 UTC, fabyan-alexander approved these changes
Approved!

2021-06-11 13:56 UTC, gabrieltron commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Config] Update Postman and docs](https://trello.com/c/TwLHdTJZ/1153-config-update-postman-and-docs)

2021-06-11 19:38 UTC, fabyan-alexander requested changes
Nice update! Just a few fixed 😄

2021-06-11 19:38 UTC, fabyan-alexander commented on docs/configurations_endpoints.md
> +      'https://api.withleaf.io/services/config/api/configs/${LEAF_USER_ID}'
Variables inside a single quote won't be replaced 😉 
```suggestion
      "https://api.withleaf.io/services/config/api/configs/${LEAF_USER_ID}"
```

2021-06-11 19:38 UTC, fabyan-alexander commented on docs/configurations_endpoints.md
> +      -H 'Authorization: Bearer ${TOKEN}' \
Variables inside a single quote won't be replaced 😉 
```suggestion
      -H "Authorization: Bearer ${TOKEN}" \
```

2021-06-11 19:38 UTC, fabyan-alexander commented on docs/configurations_endpoints.md
> +      -H 'Authorization: Bearer ${TOKEN}' \
Variables inside a single quote won't be replaced 😉 
```suggestion
      -H 'Authorization: Bearer ${TOKEN}' \
```

2021-06-11 21:03 UTC, gabrieltron commented on docs/configurations_endpoints.md
> +      'https://api.withleaf.io/services/config/api/configs/${LEAF_USER_ID}'
I was replicating a very nasty behavior that shouldn't be common in the docs, but it is, and that's not actually running those code snippets. I ran each of the snippets individually now, they all run successfully after some changes. We have more wrong snippets across the docs, this should be reviewed. bc35a888d7494b55fad60f05dc5c81adcc62c716

2021-06-11 21:03 UTC, gabrieltron commented on docs/configurations_endpoints.md
> +      -H 'Authorization: Bearer ${TOKEN}' \
Fixed on bc35a888d7494b55fad60f05dc5c81adcc62c716

2021-06-11 21:03 UTC, gabrieltron commented on docs/configurations_endpoints.md
> +      -H 'Authorization: Bearer ${TOKEN}' \
Fixed on bc35a888d7494b55fad60f05dc5c81adcc62c716

2021-06-14 13:30 UTC, fabyan-alexander approved these changes

2021-06-14 13:30 UTC, fabyan-alexander commented on docs/configurations_endpoints.md
> +      'https://api.withleaf.io/services/config/api/configs/${LEAF_USER_ID}'
Ouch, nice catch!

2021-07-26 14:31 UTC, merged