Adding new event types to Alerts
Leaf-Agriculture/docs pull request #118
Opened 2021-05-17 19:17 UTC by gbstox

Added Fields event & provider file events

2021-05-17 20:54 UTC, Dsbaule requested changes

2021-05-17 20:54 UTC, Dsbaule commented on docs/alerts_events.md
> +TAlerts for this event are in the following format:
```suggestion
Alerts for this event are in the following format:
```

2021-05-17 20:54 UTC, Dsbaule commented on docs/alerts_events.md
> +(either uploaded to provider mnaully or via Wireless Data Transfer) has successfully finished
```suggestion
(either uploaded to provider manually or via Wireless Data Transfer) has successfully finished
```

2021-05-17 20:54 UTC, Dsbaule commented on docs/alerts_events.md
> +(either uploaded to provider mnaully or via Wireless Data Transfer) is finished
```suggestion
(either uploaded to provider manually or via Wireless Data Transfer) is finished
```

2021-05-17 20:59 UTC, doodomartins commented on docs/alerts_events.md
> +  "message": "details of what happened. May be empty",
On success message we didn't return message.

```
{
  "leafUserId": "406faed2-366f-453b-a35c-3c7d1d0b58ce",
  "fileId": "b7a6741c-2bfe-4198-9e66-f4fe38104a2a",
  "type": "providerFileProcessingFinished",
  "timestamp": "2021-05-17T12:44:15.770603Z"
}
```

2021-05-17 21:00 UTC, doodomartins requested changes
Change the response on providerFileProcessingFinished

2021-05-17 21:16 UTC, gbstox reviewed
Accepted & fixed. Thank you!

2021-05-17 21:44 UTC, Dsbaule approved these changes

2021-05-18 11:56 UTC, gbstox reviewed
Updates alert response

2021-05-18 20:16 UTC, doodomartins approved these changes

2021-06-09 20:58 UTC, merged