Add new credentials endpoints and update part of old endpoints documentation
Leaf-Agriculture/docs pull request #127
Opened 2021-06-28 17:49 UTC by ricardosantacattarina

2021-06-28 17:59 UTC, ricardosantacattarina commented
![](https://github.trello.services/images/mini-trello-icon.png) [[User Management] Add new endpoints from CFV and JD](https://trello.com/c/RBNCj7U8/1175-user-management-add-new-endpoints-from-cfv-and-jd)

2021-06-28 17:59 UTC, ricardosantacattarina commented
![](https://github.trello.services/images/mini-trello-icon.png) [[User Management] Add new endpoints from CFV and JD](https://trello.com/c/RBNCj7U8/1175-user-management-add-new-endpoints-from-cfv-and-jd)

2021-06-28 17:59 UTC, ricardosantacattarina commented
![](https://github.trello.services/images/mini-trello-icon.png) [[User Management] Add new endpoints from CFV and JD](https://trello.com/c/RBNCj7U8/1175-user-management-add-new-endpoints-from-cfv-and-jd)

2021-06-29 15:27 UTC, fabyan-alexander requested changes
Nice work! But there are some points to review
* We should not use `{{url}}` in our examples as we already use api.withleaf.io
* The payload for all post endpoints is wrong, please review then
There are also some other points marked in their respective place.

2021-06-29 15:27 UTC, fabyan-alexander commented on docs/user_management_endpoints.md
> +  endpoint = 'https://{{url}}/services/usermanagement/api/users/{leafUserId}/john-deere-credentials'
There are a lot of usages of `{{url}}` while other are using `api.withleaf.io`. Which one should be used?

2021-06-29 15:27 UTC, fabyan-alexander commented on docs/user_management_endpoints.md
> +### `GET /climate-field-view-credentials`
Should we include a deprecated tag in these headers? Something like a tag or a strikethrough

2021-06-29 15:27 UTC, fabyan-alexander commented on docs/user_management_endpoints.md
> +  axios.get(endpoint, { headers, data })
What is the `data` parameter?

2021-06-29 15:27 UTC, fabyan-alexander commented on docs/user_management_endpoints.md
> +  axios.get(endpoint, { headers, data })
What is the param `data`?

2021-06-29 15:27 UTC, fabyan-alexander commented on docs/user_management_endpoints.md
> +  axios.get(endpoint, { headers, data })
What is the `data` param?

2021-06-29 15:27 UTC, fabyan-alexander commented on docs/user_management_endpoints.md
> +  }
The payload for POST endpoints is wrong for all the credentials in JD, CFV, CNHI, and Trimble and in every language. Please review then

2021-06-29 19:48 UTC, ricardosantacattarina commented on docs/user_management_endpoints.md
> +Get a Climate Field View credentials object by its id. If during a background processing for Fields or Operations file we detect that this credentials is no longer valid, the value of valid will be c
This one is still 'valid' instead of status for the old endpoint.

2021-06-29 21:10 UTC, ricardosantacattarina commented on docs/user_management_endpoints.md
> +### `GET /climate-field-view-credentials`
The first section talks about which endpoints are deprecated. For the body of the page, I think it is easier to restructure the whole page to separate deprecated endpoints from the new ones instead of tagging individually. But if you and/or product thinks every endpoint should have a tag I can add it, sure.

2021-06-29 21:11 UTC, ricardosantacattarina commented on docs/user_management_endpoints.md
> +  endpoint = 'https://{{url}}/services/usermanagement/api/users/{leafUserId}/john-deere-credentials'
Great catches :sweat_smile: , changed it to use the static URL instead of {{url}} here: https://github.com/Leaf-Agriculture/docs/pull/127/commits/9eac8b25fa0de03e858c3aab3eb7bf0c91254435

2021-06-29 21:12 UTC, ricardosantacattarina commented on docs/user_management_endpoints.md
> +Get the John Deere credentials of the Leaf User based on its id and returns a JSON with the credentials. If during a background processing for Fields or Operations file we detect that this credential
Agreed, changed it in: https://github.com/Leaf-Agriculture/docs/pull/127/commits/9eac8b25fa0de03e858c3aab3eb7bf0c91254435

2021-06-29 21:12 UTC, ricardosantacattarina commented on docs/user_management_endpoints.md
> +Get the John Deere credentials of the user based own its id and returns a JSON with the credentials. If during a background processing for Fields or Operations file we detect that this credentials is
Agreed, changed it in: https://github.com/Leaf-Agriculture/docs/pull/127/commits/9eac8b25fa0de03e858c3aab3eb7bf0c91254435

2021-06-29 21:13 UTC, ricardosantacattarina commented on docs/user_management_endpoints.md
> +Get the Climate Field View credentials of the Leaf User based on its id and returns a JSON with the credentials. If during a background processing for Fields or Operations file we detect that this cr
Agreed, changed it in: https://github.com/Leaf-Agriculture/docs/pull/127/commits/9eac8b25fa0de03e858c3aab3eb7bf0c91254435

2021-06-29 21:14 UTC, ricardosantacattarina commented on docs/user_management_endpoints.md
> +  axios.get(endpoint, { headers, data })
Great catches :sweat_smile: , those were wrong, changed it in: https://github.com/Leaf-Agriculture/docs/pull/127/commits/9eac8b25fa0de03e858c3aab3eb7bf0c91254435

2021-06-29 21:14 UTC, ricardosantacattarina commented on docs/user_management_endpoints.md
> +  axios.get(endpoint, { headers, data })
Great catches :sweat_smile: , those were wrong, changed it in: https://github.com/Leaf-Agriculture/docs/pull/127/commits/9eac8b25fa0de03e858c3aab3eb7bf0c91254435

2021-06-29 21:14 UTC, ricardosantacattarina commented on docs/user_management_endpoints.md
> +  axios.get(endpoint, { headers, data })
Great catches :sweat_smile: , those were wrong, changed it in: https://github.com/Leaf-Agriculture/docs/pull/127/commits/9eac8b25fa0de03e858c3aab3eb7bf0c91254435

2021-06-29 21:15 UTC, ricardosantacattarina commented on docs/user_management_endpoints.md
> +  }
Finally, the last one, this wasn't as bad as it seemed :smile: , changed it in: https://github.com/Leaf-Agriculture/docs/pull/127/commits/9eac8b25fa0de03e858c3aab3eb7bf0c91254435

2021-06-30 12:52 UTC, fabyan-alexander commented on docs/user_management_endpoints.md
> +### `GET /climate-field-view-credentials`
Your right!

2021-06-30 13:05 UTC, fabyan-alexander approved these changes

2021-07-14 17:37 UTC, merged