Add JD prescription endpoints
Leaf-Agriculture/docs pull request #174
Opened 2021-12-07 16:33 UTC by palomacione

2021-12-07 16:33 UTC, palomacione commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Docs] Add prescription upload endpoints to JD](https://trello.com/c/JhiBg0F5/304-docs-add-prescription-upload-endpoints-to-jd)

2021-12-07 16:44 UTC, fabyan-alexander commented on docs/beta_prescriptions_endpoints.md
> +    "name": "str"
Nice :smile:

2021-12-07 16:44 UTC, fabyan-alexander commented on docs/beta_prescriptions_endpoints.md
> +[6]: #upload-prescription-to-john-deere
These are hard to keep track

2021-12-07 16:47 UTC, fabyan-alexander commented on docs/beta_prescriptions_endpoints.md
> +  const endpoint ='https://api.withleaf.io/services/beta/prescriptions/api/users/{leafUserId}/johnDeere'
This endpoint requires the request param **organizationId**

2021-12-07 16:47 UTC, fabyan-alexander commented on docs/beta_prescriptions_endpoints.md
> +  endpoint = 'https://api.withleaf.io/services/beta/prescriptions/api/users/{leafUserId}/johnDeere'
This endpoint requires the request param **organizationId**

2021-12-07 16:47 UTC, fabyan-alexander commented on docs/beta_prescriptions_endpoints.md
> +      'https://api.withleaf.io/services/beta/prescriptions/api/users/{leafUserId}/johnDeere'
This endpoint requires the request param **organizationId**

2021-12-07 16:50 UTC, fabyan-alexander requested changes
Nice work!
Just a missing property in the upload of prescription to review :smile:

2021-12-07 16:50 UTC, fabyan-alexander commented on docs/beta_prescriptions_endpoints.md
> +Upload a prescription using the John Deere credentials of the LeafUserId.
There is a required request param called **organizationId** for this endpoint to work.
This property should be the id of the organization at JohnDeere

2021-12-07 17:02 UTC, palomacione commented on docs/beta_prescriptions_endpoints.md
> +Upload a prescription using the John Deere credentials of the LeafUserId.
04f41a513aba113bba4776f2fb351fd7dc642fe5

2021-12-07 17:04 UTC, fabyan-alexander approved these changes

2021-12-07 17:58 UTC, ricardosantacattarina approved these changes

2021-12-07 17:58 UTC, ricardosantacattarina commented on docs/beta_prescriptions_endpoints.md
> +      -d '{ "name": "str"}' \
```suggestion
```
I remember we discussed about what should be in the body of a GET request, I think we should remove every case of this -d parameter on GET requests.

2021-12-07 20:11 UTC, Vinniekun approved these changes

2021-12-07 21:42 UTC, fabyan-alexander commented on docs/beta_prescriptions_endpoints.md
> +      -d '{ "name": "str"}' \
+1

2021-12-08 12:43 UTC, palomacione commented on docs/beta_prescriptions_endpoints.md
> +      -d '{ "name": "str"}' \
280dd7a66d40a689cfe43af47d947c3fbc86ed46

2021-12-08 17:28 UTC, fabyan-alexander approved these changes

2021-12-08 17:28 UTC, merged