Change registration url to /register
Leaf-Agriculture/docs pull request #175
Opened 2021-12-08 17:32 UTC by gabrieltron

2021-12-08 18:17 UTC, CarlosSam requested changes

2021-12-08 18:17 UTC, CarlosSam commented on docs/quickstart.md
> +First, please [register on our website](https://leafagriculture.com.br/register/) to receive your credentials.
```suggestion
First, please [register on our website](https://withleaf.io/register/) to receive your credentials.
```
the url you wrote does not exists

2021-12-08 18:17 UTC, CarlosSam commented on docs/authentication.md
> +[register]: https://leafagriculture.com.br/register/
```suggestion
[register]: https://withleaf.io/register/
```
the url you wrote does not exists

2021-12-08 18:17 UTC, CarlosSam commented on docusaurus.config.js
> +        //   to: 'https://leafagriculture.com.br/register/',
why not use the withleaf.io/register in this one too?

2021-12-08 19:16 UTC, gabrieltron commented on docs/quickstart.md
> +First, please [register on our website](https://leafagriculture.com.br/register/) to receive your credentials.
Nice catch. I tested the register button but not the ones in the docs. Fixed it in 8721832

2021-12-08 19:16 UTC, gabrieltron commented on docs/authentication.md
> +[register]: https://leafagriculture.com.br/register/
Fixed in 8721832

2021-12-08 19:16 UTC, gabrieltron commented on docusaurus.config.js
> +        //   to: 'https://leafagriculture.com.br/register/',
Fixed in  8721832

2021-12-09 22:31 UTC, gabrieltron commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Docs] Update Leaf's URL](https://trello.com/c/NyCa61Nt/1755-docs-update-leafs-url)

2021-12-10 13:25 UTC, merged