Add Farm and Grower CRUD to documentation.
Leaf-Agriculture/docs pull request #187
Opened 2022-01-05 15:07 UTC by LuisOw

(cherry picked from commit db08361fda27c9858175e3a7f2e706e7bd850640)

2022-01-07 20:10 UTC, vitorezende commented on docs/field_boundaries_endpoints.md
> +Creates a grower for the user `leafUserId`. It's possible to pass `name` on the body of the request. The body can be empty.
Testing this endpoint and if the request body is empty a Bad Request is returned with message "Required request body is missing".
I think it would be nice to add a request body example even though all the fields are not required.

2022-01-07 20:10 UTC, vitorezende commented on docs/field_boundaries_endpoints.md
> +the request. The body can be empty.
Testing this endpoint and if the request body is empty a Bad Request is returned with message "Required request body is missing".
I think it would be nice to add a request body example even though all the fields are not required.

2022-01-07 20:10 UTC, vitorezende commented on docs/field_boundaries_endpoints.md
> +Updates the farm with id `id` for the user `leafUserId`. It's possible to pass both the `farmName` and the `growerId`
I think it would be nice to add a request body example.

2022-01-07 20:10 UTC, vitorezende commented on docs/field_boundaries_endpoints.md
> +Updates the grower with id `id` for the user `leafUserId`. It's possible to pass only the `name` on the body of the request.
I think it would be nice to add a request body example.

2022-01-10 17:51 UTC, vitorezende approved these changes

2022-01-11 20:05 UTC, gabrieltron requested changes
Nice! I have a few comments we should go through

2022-01-12 19:16 UTC, vitorezende commented on docs/field_boundaries_endpoints.md
> +[18]: #delete-a-farm
https://github.com/Leaf-Agriculture/docs/pull/187/commits/d1ff73be046fcd996130d57b331294fee04a23fb

2022-01-12 19:16 UTC, vitorezende commented on docs/field_boundaries_endpoints.md
> +      -d '{ "name": "farmName", "growerId": "growerId }'
https://github.com/Leaf-Agriculture/docs/pull/187/commits/d1ff73be046fcd996130d57b331294fee04a23fb

2022-01-12 19:16 UTC, vitorezende commented on docs/field_boundaries_endpoints.md
> +    'growerId': 'growerId'
https://github.com/Leaf-Agriculture/docs/pull/187/commits/d1ff73be046fcd996130d57b331294fee04a23fb

2022-01-12 19:16 UTC, vitorezende commented on docs/field_boundaries_endpoints.md
> +    growerId: growerId
https://github.com/Leaf-Agriculture/docs/pull/187/commits/d1ff73be046fcd996130d57b331294fee04a23fb

2022-01-12 19:16 UTC, vitorezende commented on docs/field_boundaries_endpoints.md
> +    name: newFarmName,
https://github.com/Leaf-Agriculture/docs/pull/187/commits/d1ff73be046fcd996130d57b331294fee04a23fb

2022-01-12 21:18 UTC, gabrieltron approved these changes
Nice!

2022-01-12 21:18 UTC, merged