Add filter fields and pagination
Leaf-Agriculture/docs pull request #197
Opened 2022-01-31 18:45 UTC by ricardosantacattarina

2022-01-31 18:46 UTC, ricardosantacattarina commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Docs] Include endpoints with filter](https://trello.com/c/D1iZY2Ya/454-docs-include-endpoints-with-filter)

2022-01-31 21:51 UTC, fabyan-alexander requested changes
Nice update!
I think we could improve the description =]

2022-01-31 21:51 UTC, fabyan-alexander commented on docs/beta_machines_endpoints.md
> +- `afterCreatedAt`, filters for records created after the datetime
Should we repeat the text "to filter by"?
Maybe we could pass the supported value, like **text/uuid/iso8601**, what do you think?

2022-01-31 21:51 UTC, fabyan-alexander commented on docs/beta_machines_endpoints.md
> +- `afterCreatedAt`, filters for records created after the datetime
Should we repeat the text "to filter by"?
Maybe we could pass the supported value, like **text/uuid/iso8601**, what do you think?

2022-02-01 16:42 UTC, ricardosantacattarina commented on docs/beta_machines_endpoints.md
> +- `afterCreatedAt`, filters for records created after the datetime
https://github.com/Leaf-Agriculture/docs/pull/197/commits/aba8e341ecbced2a5092fa0e18c0c1a88fe1de73 what about now?

2022-02-01 16:43 UTC, ricardosantacattarina commented on docs/beta_machines_endpoints.md
> +- `afterCreatedAt`, filters for records created after the datetime
https://github.com/Leaf-Agriculture/docs/pull/197/commits/aba8e341ecbced2a5092fa0e18c0c1a88fe1de73 what about now?

2022-02-01 19:55 UTC, fabyan-alexander commented on docs/beta_machines_endpoints.md
> +- `afterCreatedAt`, filters for records created after the datetime
It is nice!

2022-02-01 19:55 UTC, fabyan-alexander commented on docs/beta_machines_endpoints.md
> +- `afterCreatedAt`, filters for records created after the datetime
It is nice!

2022-02-01 19:55 UTC, fabyan-alexander approved these changes

2022-02-01 19:59 UTC, merged