update machine files filters
Leaf-Agriculture/docs pull request #201
Opened 2022-02-22 18:01 UTC by palomacione

2022-02-22 18:02 UTC, palomacione commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Docs] Update the machine files filters to include distance and periods of start time/end time](https://trello.com/c/fDwsige8/497-docs-update-the-machine-files-filters-to-include-distance-and-periods-of-start-time-end-time)

2022-02-22 19:42 UTC, ricardosantacattarina reviewed
Nice job, I'm just not quite sure on how to describe these new fields

2022-02-22 19:42 UTC, ricardosantacattarina commented on docs/beta_machines_endpoints.md
> +| `distanceValue` |  a double value for the distance |
I think we should we create a tech debt card to allow period filtering for double values too.

2022-02-22 19:42 UTC, ricardosantacattarina commented on docs/beta_machines_endpoints.md
> +| `afterEndtime` |  an ISO 8601 without timezone, returns all machine files that ended after the specified time |
What do you mean by machine files that started or ended? because that's the operation start time and end time, I don't think it is clear enough

2022-02-23 12:59 UTC, palomacione commented on docs/beta_machines_endpoints.md
> +| `afterEndtime` |  an ISO 8601 without timezone, returns all machine files that ended after the specified time |
yes, I meant operations, I'll change that

2022-02-23 13:14 UTC, palomacione commented on docs/beta_machines_endpoints.md
> +| `afterEndtime` |  an ISO 8601 without timezone, returns all machine files that ended after the specified time |
https://github.com/Leaf-Agriculture/docs/pull/201/commits/389e4430286dad1acb07e0cc581dd1902ae7996f

2022-02-23 18:26 UTC, ricardosantacattarina commented on docs/beta_machines_endpoints.md
> +| `distanceUnit` | must be "Mile", "mile", "Feet" or "ft" |
```suggestion
| `distanceUnit` | must be "Mile", "mile", "Feet" or "ft" |
```
does all 4 of these types work?

2022-03-07 13:52 UTC, ricardosantacattarina requested changes
Only MILE and FEET should be available, the other 2 didn't work on my tests. This is somewhat inconsistent, as the response shows the unit type as "ft" or "mile".

2022-03-07 13:52 UTC, ricardosantacattarina commented on docs/beta_machines_endpoints.md
> +| `distanceUnit` | must be "Mile", "mile", "Feet" or "ft" |
```suggestion
| `distanceUnit` | must be "MILE" or "FEET" |
```

2022-03-11 14:08 UTC, ricardosantacattarina approved these changes

2022-03-17 13:35 UTC, merged