Getting historical images when creating new field in the satellite
Leaf-Agriculture/docs pull request #36
Opened 2020-09-10 14:21 UTC by acebr1

2020-09-10 15:57 UTC, acebr1 commented on docs/satellite_endpoints.md
> +as you want.
Nice

2020-09-10 16:25 UTC, meyer1994 requested changes

2020-09-10 16:25 UTC, meyer1994 commented on docs/satellite_endpoints.md
> +bigger than 5k hectares (12.3k acres) and it cannot have a perimeter bigger
50k hectares

2020-09-10 16:25 UTC, meyer1994 commented on docs/satellite_endpoints.md
> +than 28km (17.4 miles).
89km, which is the result of:
```py
sqrt(500_000_000) * 4
```
Which is the perimeter of an square with 50k hecates of area.

2020-09-10 16:25 UTC, meyer1994 commented on docs/satellite_overview.md
> +We also provide information like percent cloud coverage of the field, and the Sentinel tile source for each image.
Data coverage percentage as well.

2020-09-10 17:01 UTC, acebr1 commented on docs/satellite_endpoints.md
> +bigger than 5k hectares (12.3k acres) and it cannot have a perimeter bigger
![Captura de tela de 2020-09-10 14-01-25](https://user-images.githubusercontent.com/4976228/92768182-29b68100-f36e-11ea-85b5-b2bc69ae9fba.png)

2020-09-10 17:03 UTC, acebr1 commented on docs/satellite_endpoints.md
> +bigger than 5k hectares (12.3k acres) and it cannot have a perimeter bigger
![Captura de tela de 2020-09-10 14-02-47](https://user-images.githubusercontent.com/4976228/92768403-5cf91000-f36e-11ea-8d2d-a7c001ba85bd.png)

2020-09-10 17:09 UTC, acebr1 commented on docs/satellite_endpoints.md
> +than 28km (17.4 miles).
sqrt(50_000_000) * 4 = 28284

2020-09-10 18:49 UTC, meyer1994 approved these changes

2020-09-11 14:03 UTC, GMBueno approved these changes

2020-09-11 15:32 UTC, merged