Add documentation for Farms
Leaf-Agriculture/docs pull request #44
Opened 2020-09-18 17:42 UTC by gabrieltron

This PR is to add documentation for Farms. While we were working on it, we noticed that we still need to implement multi-tenancy on Farm and Growers before it's safe to make the documentation available. Here's the work on the documentation so far, it'll be improved once multi-tenancy is implemented.

2020-09-30 22:08 UTC, ramnasidharta approved these changes
Well done, mate! (Approved. Please consider my comments and note that you commited `.idea` files, those can be ignored)

2020-09-30 22:08 UTC, ramnasidharta commented on docs/field_boundaries_endpoints.md
> +```json
I think that for reasons of markdown syntax it's better or necessary to have one blank line here
```suggestion
Form of a Farm:

```json
```

2020-09-30 22:08 UTC, ramnasidharta commented on docs/field_boundaries_endpoints.md
> +  const headers = { 'Authorization': `Bearer ${TOKEN}` }
```suggestion
  const headers = { 'Authorization': 'Bearer ${TOKEN}' }
```

2020-09-30 22:08 UTC, ramnasidharta commented on docs/field_boundaries_endpoints.md
> +  const headers = { 'Authorization': `Bearer ${TOKEN}` }
Same in other places

2020-09-30 22:08 UTC, ramnasidharta commented on docs/field_boundaries_endpoints.md
> +Creates a Farm. The request's body can provide values for the farm
```suggestion
Creates a Farm. The request's body provides values for the farm
```

2020-10-01 13:30 UTC, GMBueno commented on docs/field_boundaries_endpoints.md
> +  "providerFarmId": "UUID",
can we remove this from the response? It's unnecessary, from my perspective....

2020-10-01 13:30 UTC, GMBueno commented on docs/field_boundaries_endpoints.md
> +  "providerFarmId": "UUID",
I am referring to "providerFarmId", this is the id of the farm on the provider right?

2020-10-01 13:32 UTC, GMBueno commented on docs/field_boundaries_endpoints.md
> +  "providerName": "str",
we have to define if the convention will be "providerName" or "provider"... we have both now

2020-10-01 14:43 UTC, ramnasidharta commented on docs/field_boundaries_endpoints.md
> +  "providerFarmId": "UUID",
Yes, it is. Why unnecessary? datasync can create farms, so they will have this attribute set

2020-10-01 14:43 UTC, ramnasidharta commented on docs/field_boundaries_endpoints.md
> +  "providerName": "str",
Yep. I vote for `provider`

2020-10-01 18:53 UTC, GMBueno requested changes
good job! I added a few comments/questions I would like to know before approving 😄

2020-10-01 19:02 UTC, ramnasidharta commented on docs/field_boundaries_endpoints.md
> +### `DELETE users/{leafUserId}/farms/{id}`
"Only at leaft" for the 1st question. "Maybe" for the 2nd. If that farm was created from pooling then yes, we do will create it again. We know 0 real use case for datasync, so I think documenting this kind of endpoint are 100% a product decision. The fact is that all endpoint that allows writting are conflicting with datasync. Currently we're simply ignoring this fact.

2020-10-01 19:06 UTC, ramnasidharta commented on docs/field_boundaries_endpoints.md
> +### `POST users/{leafUserId}/farms`
Nope, although we can add a farm to a field on field creation. Does this functionality you're asking about make sense?

2020-10-01 19:07 UTC, ramnasidharta commented on docs/field_boundaries_endpoints.md
> +### `PUT users/{leafUserId}/farms`
Nope

2020-10-05 21:11 UTC, meyer1994 requested changes

2020-10-05 21:11 UTC, meyer1994 commented on docs/field_boundaries_endpoints.md
> -  const headers = { 'Authorization': `Bearer ${TOKEN}` }
Why have you changed this? It is valid JavaScript

2020-10-05 21:28 UTC, ramnasidharta commented on docs/field_boundaries_endpoints.md
> -  const headers = { 'Authorization': `Bearer ${TOKEN}` }
Approve it

2020-10-05 22:36 UTC, meyer1994 approved these changes

2020-10-06 19:24 UTC, GMBueno approved these changes

2020-10-06 20:06 UTC, merged