add_summarize_product_config
Leaf-Agriculture/docs pull request #446
Opened 2023-07-06 20:10 UTC by allanpetersoon

2023-07-06 20:15 UTC, gustavorodriguespereira approved these changes

2023-07-07 12:09 UTC, guthierry requested changes

2023-07-07 12:09 UTC, guthierry commented on docs/configurations_overview.md
> +for area we will do the average and for totalApplied we will do the sum. This config is only available for applied type operations. The default value is `false`.
how about the rates?

2023-07-07 12:49 UTC, allanpetersoon commented on docs/configurations_overview.md
> +for area we will do the average and for totalApplied we will do the sum. This config is only available for applied type operations. The default value is `false`.
good, i already added

2023-07-07 19:10 UTC, guthierry approved these changes

2023-07-07 19:46 UTC, merged