New sync endpoint and Stara app keys updates
Leaf-Agriculture/docs pull request #553
Opened 2024-09-12 13:38 UTC by guthierry

- New sync endpoint to enable preview fields based on the grower's list
- Stara app keys fixed for Link and Magic Link

2024-09-12 16:11 UTC, awimbush requested changes
Please make edits.  Do we have Leaf Grower IDs or are these Leaf User IDs?

2024-09-12 16:11 UTC, awimbush commented on docs/field_boundary_management_endpoints.md
> +Fields can also be marked to synchronization at the grower level using the [enable preview fields by growers](#enable-preview-fields-by-grower) endpoint.
Edit:  "Fields can be set to synchronize at the grower level.."

2024-09-16 12:10 UTC, guthierry commented on docs/field_boundary_management_endpoints.md
> +It will remove the indicated growers' fields from `PREVIEW` mode leaving them ready to be fetched almost immediately after the request. The status will change to `WAITING`. It accepts a list of Leaf
yes, we have growers IDs. A single leaf user can have multiple growers, especially in John Deere where the orgs are mapped as growers.

2024-09-16 12:56 UTC, gustavorodriguespereira approved these changes

2024-09-16 14:58 UTC, awimbush approved these changes

2024-09-16 14:58 UTC, merged