Provider Organization Sync Feature Documentaion
Leaf-Agriculture/docs pull request #556
Opened 2024-10-10 21:15 UTC by gustavorodriguespereira

- First commit 518c281319bfe6d5bdcaa83d3d9cb61f0625142e, we have the config overview
- Second commit ca2bbf80e2b8fab30047aa5b65dd9d9c7c336f8b, we have the endpoints

2024-10-11 15:57 UTC, awimbush commented on docs/configurations_overview.md
> +If set to `ALL`, Leaf will fetch organizations from the provider account with the default processing behavior for the resources with the status set as `SELECTED`. When set to `SELECTED_ONLY` the API
If set to 'ALL', Leaf will fetch and process data from all organizations within the provider account.  If set to 'SELECTED_ONLY', Leaf will only fetch and process data from the organizations were the organization status has been set to 'SELECTED'.  Setting the status of an organization is done using the Organization Sync endpoints.

2024-10-11 15:59 UTC, awimbush commented on docs/provider_organizations.md
> +The endpoints described here are separated into two disticnt categories, the [Organizations List][2] are tools for listing organizations that have or have not granted access to Leaf. Additionaly we h
The endpoints described here are divided into two categories. The [Organizations List][2] provides tools for listing organizations that have or have not granted access to Leaf. The [Organization Sync][3] offers tools for managing organizations to be processed, which in turn impacts associated resources such as field boundaries, operations, and assets.

2024-10-11 17:36 UTC, gustavorodriguespereira commented on docs/provider_organizations.md
> +The endpoints described here are separated into two disticnt categories, the [Organizations List][2] are tools for listing organizations that have or have not granted access to Leaf. Additionaly we h
Changes executed with the 46c5dfefa9674ecb474c230a595c724fd044ca36 commit

2024-10-11 17:37 UTC, gustavorodriguespereira commented on docs/configurations_overview.md
> +If set to `ALL`, Leaf will fetch organizations from the provider account with the default processing behavior for the resources with the status set as `SELECTED`. When set to `SELECTED_ONLY` the API
Changes executed with the 46c5dfefa9674ecb474c230a595c724fd044ca36 commit

2024-10-14 20:54 UTC, guthierry approved these changes

2024-10-15 12:09 UTC, awimbush requested changes
Please make edits.

2024-10-15 12:09 UTC, awimbush commented on docs/provider_organizations.md
> +Here's the properties available for a Provider Organization.
EDIT: The properties available for a Provider Organization are:

2024-10-15 12:09 UTC, awimbush commented on docs/provider_organizations.md
> +- The `provider_org_id` property is referecing the organization id value from the provider. It should be used while managing this resource.
The 'provider_org_id' property references the organization ID value from the provider.  For example, if the John Deere organization ID is 12345, then the 'provider_org_id' should be 12345.

2024-10-15 12:09 UTC, awimbush commented on docs/provider_organizations.md
> +- The `provider_org_name` property is referecing the organization name value from the provider.
The 'provider_org_name' property references the value of the organization name from the provider.

2024-10-15 12:09 UTC, awimbush commented on docs/provider_organizations.md
> +- The `status` property is refrencing to the current state of the resource. The property can have multiple values between `PREVIEW`, `SELECTED` and `BLOCKED`.
The 'status' property represents the current state of the resource.  The state of the resource can be either 'PREVIEW', 'SELECTED', or 'BLOCKED'.

2024-10-15 12:09 UTC, awimbush commented on docs/provider_organizations.md
> +  - If the `status` property has the value `SELECTED`, all the resources available to be fecthed from the provider will be processed.
If the 'status' property has the value 'SELECTED', all available resources will be fetched from the provider and processed.

2024-10-15 12:09 UTC, awimbush commented on docs/provider_organizations.md
> +  - If the `status` property has the value `PREVIEW`, no resources beyond the organization itsefl will be processed.
@gustavorodriguespereira I don't understand what this means.

2024-10-15 12:09 UTC, awimbush commented on docs/provider_organizations.md
> +  - If the `status` property has the value `BLOCKED`, the organization does not have the required permissions in order to be processed by Leaf API, to troubleshoot this issue please review the Step 3
- If the `status` property has the value `BLOCKED`, the organization does not have the required permissions to be processed by Leaf.  To troubleshoot this issue please review Step 3 of the [John Deere Authentication Guide][7], once the setup is complete, the resource will be available with the `PREVIEW` status. For any additional troubleshooting options, please reach out to help@withleaf.io

2024-10-15 12:09 UTC, awimbush commented on docs/provider_organizations.md
> +With this endpoint, users can select a provider organization individually.
With this endpoint users can retrieve individual provider organizations.

2024-10-15 12:09 UTC, awimbush commented on docs/provider_organizations.md
> +With this endpoint users can check the organizations ingested from the integration process.
With this endpoint users can retrieve all organizations.

2024-10-16 13:05 UTC, awimbush approved these changes

2024-10-16 13:09 UTC, merged